name: Jimit Vyas
title: Senior Virtual Analyst - FEA | Automation & Scripting Specialist | CAEâ€“AI Integration
email: jimit.vyas@outlook.com
phone: "+91 8200500169"
linkedin_url: https://linkedin.com/in/jimit04
linkedin_handle: linkedin.com/in/jimit04
location: Bangalore, India
